language: python

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - git
      - libyaml-dev
      - python-dev
      - python-pip
      - python-lxml

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update           ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install coreutils; fi

script:
  - ls
  - python setup.py install