sudo: required

language: python

python:
  - "2.7"

services:
  - docker

#addons:
#  hosts:
#    - galaxy

env:
  global:
    - GALAXY_CONFIG_MASTER_API_KEY=HSNiugRFvgT574F43jZ7N9F3
    - GALAXY_NETWORK=galaxy
    - GALAXY_PORT=30700
    - GALAXY_DOCKER_HOST=prova
    - GALAXY_URL=http://${GALAXY_DOCKER_HOST}:${GALAXY_PORT}
    - GALAXY_CONTAINER_NAME=galaxy-server
    - GALAXY_USERNAME=wft4galaxy
    - GALAXY_USER_PASSWORD=wft4galaxy-tester
    - GALAXY_USER_EMAIL=wft4galaxy@wft.it

#  matrix:
#    - USE_NETWORK=true
#    - USE_NETWORK=false

before_install:
- docker network create --driver bridge --subnet=172.18.0.0/16 ${GALAXY_NETWORK}
- docker run -itd --network ${GALAXY_NETWORK} --ip 172.18.0.22 --hostname ${GALAXY_DOCKER_HOST} --name ${GALAXY_CONTAINER_NAME} ubuntu

install:
#- python setup.py install

script:
- docker run -it --network ${GALAXY_NETWORK} --rm ubuntu bash -c "apt-get update && apt-get install -y inetutils-ping && timeout 10 ping 172.18.0.22"


after_script:
- docker rm -f ${GALAXY_CONTAINER_NAME}